<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.0.309
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Home Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'fahadkhalidmalik@gmail.com',
		'to' => 'fahadkhalidmalik@gmail.com'
	),
	'fields' => array(
		'custom_U268' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'First Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'First Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 4,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U498' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Last Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Last Name\' is required.'
			)
		),
		'custom_U502' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Address\' is required.'
			)
		),
		'custom_U530' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Phone number',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Phone number\' is required.'
			)
		),
		'custom_U722' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Other',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Other\' is required.'
			)
		),
		'custom_U423' => array(
			'order' => 6,
			'type' => 'checkboxgroup',
			'label' => 'City',
			'required' => true,
			'optionItems' => array(
				'Abu Dhabi',
				'Ajman',
				'Al Ain',
				'Dubai',
				'Fujairah',
				'Ras Al Khaimah',
				'Sharjah',
				'Umm al Quwain'
			),
			'errors' => array(
				'required' => 'Field \'City\' is required.',
				'format' => 'Field \'City\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
